--------------------------------------------------------------------------------
-- Forms2APEX Accelerator
-- Migration : 001_audit_timestamps_with_timezone.sql
-- Purpose   : Convert technical audit timestamps from TIMESTAMP
--             to TIMESTAMP WITH TIME ZONE
-- Version   : 0.1
--
-- Important:
-- Existing timestamps were generated by SYSTIMESTAMP while the Oracle
-- container was running in UTC. Therefore existing TIMESTAMP values
-- are interpreted explicitly as UTC (+00:00) during this migration.
--------------------------------------------------------------------------------


--------------------------------------------------------------------------------
-- F2A_PROJECT
--------------------------------------------------------------------------------

ALTER TABLE F2A_PROJECT ADD
(
    CREATED_AT_TZ TIMESTAMP WITH TIME ZONE,
    UPDATED_AT_TZ TIMESTAMP WITH TIME ZONE
);

UPDATE F2A_PROJECT
SET
    CREATED_AT_TZ =
        FROM_TZ(CREATED_AT, '+00:00'),

    UPDATED_AT_TZ =
        CASE
            WHEN UPDATED_AT IS NOT NULL
            THEN FROM_TZ(UPDATED_AT, '+00:00')
        END;

COMMIT;

ALTER TABLE F2A_PROJECT DROP COLUMN CREATED_AT;
ALTER TABLE F2A_PROJECT DROP COLUMN UPDATED_AT;

ALTER TABLE F2A_PROJECT
RENAME COLUMN CREATED_AT_TZ TO CREATED_AT;

ALTER TABLE F2A_PROJECT
RENAME COLUMN UPDATED_AT_TZ TO UPDATED_AT;

ALTER TABLE F2A_PROJECT MODIFY
(
    CREATED_AT DEFAULT SYSTIMESTAMP NOT NULL
);


--------------------------------------------------------------------------------
-- F2A_SOURCE_FILE
--------------------------------------------------------------------------------

ALTER TABLE F2A_SOURCE_FILE ADD
(
    CREATED_AT_TZ TIMESTAMP WITH TIME ZONE,
    PARSED_AT_TZ  TIMESTAMP WITH TIME ZONE
);

UPDATE F2A_SOURCE_FILE
SET
    CREATED_AT_TZ =
        FROM_TZ(CREATED_AT, '+00:00'),

    PARSED_AT_TZ =
        CASE
            WHEN PARSED_AT IS NOT NULL
            THEN FROM_TZ(PARSED_AT, '+00:00')
        END;

COMMIT;

ALTER TABLE F2A_SOURCE_FILE DROP COLUMN CREATED_AT;
ALTER TABLE F2A_SOURCE_FILE DROP COLUMN PARSED_AT;

ALTER TABLE F2A_SOURCE_FILE
RENAME COLUMN CREATED_AT_TZ TO CREATED_AT;

ALTER TABLE F2A_SOURCE_FILE
RENAME COLUMN PARSED_AT_TZ TO PARSED_AT;

ALTER TABLE F2A_SOURCE_FILE MODIFY
(
    CREATED_AT DEFAULT SYSTIMESTAMP NOT NULL
);


--------------------------------------------------------------------------------
-- F2A_FORM
--------------------------------------------------------------------------------

ALTER TABLE F2A_FORM ADD
(
    CREATED_AT_TZ TIMESTAMP WITH TIME ZONE
);

UPDATE F2A_FORM
SET CREATED_AT_TZ =
    FROM_TZ(CREATED_AT, '+00:00');

COMMIT;

ALTER TABLE F2A_FORM DROP COLUMN CREATED_AT;

ALTER TABLE F2A_FORM
RENAME COLUMN CREATED_AT_TZ TO CREATED_AT;

ALTER TABLE F2A_FORM MODIFY
(
    CREATED_AT DEFAULT SYSTIMESTAMP NOT NULL
);


--------------------------------------------------------------------------------
-- End migration
--------------------------------------------------------------------------------