from __future__ import annotations

from collections import Counter
from dataclasses import dataclass
from pathlib import Path
from typing import Sequence

from f2a.reporting.assessment import AssessmentSummary


@dataclass(frozen=True)
class PortfolioSummary:
    total_files: int
    successful_forms: int
    failed_forms: int

    total_findings: int
    total_builtins: int
    total_behaviors: int
    total_effort: int

    complexity_summary: tuple[
        tuple[str, int], ...
    ]

    risk_summary: tuple[
        tuple[str, int], ...
    ]

    classification_summary: tuple[
        tuple[str, int], ...
    ]

    forms: tuple[
        AssessmentSummary, ...
    ]

    migration_waves: tuple[
        tuple[str, str],
        ...
    ]


def _counter_as_tuple(
    counter: Counter,
) -> tuple[tuple[str, int], ...]:

    return tuple(
        sorted(
            counter.items()
        )
    )

def _get_migration_wave(
    summary: AssessmentSummary,
) -> str:

    if (
        summary.overall_risk == "HIGH"
        or summary.overall_complexity == "HIGH"
        or summary.total_effort >= 12
    ):
        return "WAVE_3"

    if (
        summary.overall_risk == "MEDIUM"
        or summary.overall_complexity == "MEDIUM"
        or summary.total_effort >= 6
    ):
        return "WAVE_2"

    return "WAVE_1"


def build_portfolio_summary(
    summaries: Sequence[AssessmentSummary],
    *,
    total_files: int,
    failed_forms: int,
) -> PortfolioSummary:

    forms = tuple(
        sorted(
            summaries,
            key=lambda summary: summary.form_name,
        )
    )

    complexity_counter = Counter(
        summary.overall_complexity
        for summary in forms
    )

    risk_counter = Counter(
        summary.overall_risk
        for summary in forms
    )

    classification_counter = Counter(
        summary.assessment_classification
        for summary in forms
    )

    migration_waves = tuple(
        (
            summary.form_name,
            _get_migration_wave(
                summary
            ),
        )
        for summary in forms
    )

    return PortfolioSummary(
        total_files=total_files,
        successful_forms=len(forms),
        failed_forms=failed_forms,
        total_findings=sum(
            summary.finding_count
            for summary in forms
        ),
        total_builtins=sum(
            summary.builtin_count
            for summary in forms
        ),
        total_behaviors=sum(
            summary.behavior_count
            for summary in forms
        ),
        total_effort=sum(
            summary.total_effort
            for summary in forms
        ),
        complexity_summary=_counter_as_tuple(
            complexity_counter
        ),
        risk_summary=_counter_as_tuple(
            risk_counter
        ),
        classification_summary=_counter_as_tuple(
            classification_counter
        ),
        forms=forms,
        migration_waves=migration_waves,
    )


def _render_distribution(
    title: str,
    values: tuple[tuple[str, int], ...],
) -> list[str]:

    lines = [
        f"## {title}",
        "",
        "| Classification | Forms |",
        "|---|---:|",
    ]

    if not values:
        lines.append(
            "| None | 0 |"
        )
    else:
        for name, count in values:
            lines.append(
                f"| {name} | {count} |"
            )

    lines.append("")

    return lines


def render_portfolio_markdown(
    portfolio: PortfolioSummary,
) -> str:

    lines: list[str] = [
        "# Forms2APEX Portfolio Assessment",
        "",
        "Generated by Forms2APEX Accelerator.",
        "",
        "## Portfolio Overview",
        "",
        "| Metric | Value |",
        "|---|---:|",
        (
            f"| XML Files Discovered | "
            f"{portfolio.total_files} |"
        ),
        (
            f"| Forms Assessed | "
            f"{portfolio.successful_forms} |"
        ),
        (
            f"| Forms Failed | "
            f"{portfolio.failed_forms} |"
        ),
        (
            f"| Migration Findings | "
            f"{portfolio.total_findings} |"
        ),
        (
            f"| Forms Built-ins | "
            f"{portfolio.total_builtins} |"
        ),
        (
            f"| Behavior Patterns | "
            f"{portfolio.total_behaviors} |"
        ),
        (
            f"| Total Effort Points | "
            f"{portfolio.total_effort} |"
        ),
        "",
    ]

    lines.extend(
        _render_distribution(
            "Complexity Distribution",
            portfolio.complexity_summary,
        )
    )

    lines.extend(
        _render_distribution(
            "Risk Distribution",
            portfolio.risk_summary,
        )
    )

    lines.extend(
        _render_distribution(
            "Migration Classification",
            portfolio.classification_summary,
        )
    )

    lines.extend(
        [
            "## Forms",
            "",
            (
                "| Form | Complexity | Risk | "
                "Classification | Findings | Effort |"
            ),
            "|---|---|---|---|---:|---:|",
        ]
    )

    lines.extend(
        [
            "",
            "## Suggested Migration Waves",
            "",
            "| Form | Suggested Wave |",
            "|---|---|",
        ]
    )

    for form_name, wave in portfolio.migration_waves:

        lines.append(
            f"| {form_name} | {wave} |"
        )

    for summary in portfolio.forms:

        lines.append(
            (
                f"| {summary.form_name} "
                f"| {summary.overall_complexity} "
                f"| {summary.overall_risk} "
                f"| {summary.assessment_classification} "
                f"| {summary.finding_count} "
                f"| {summary.total_effort} |"
            )
        )

    lines.extend(
        [
            "",
            "## Portfolio Status",
            "",
        ]
    )

    if portfolio.failed_forms:
        lines.append(
            (
                "**Portfolio assessment completed "
                "with processing errors.**"
            )
        )
    else:
        lines.append(
            "**Portfolio assessment completed successfully.**"
        )

    lines.append("")

    return "\n".join(lines)


def generate_portfolio_file(
    summaries: Sequence[AssessmentSummary],
    *,
    total_files: int,
    failed_forms: int,
    output_dir: Path,
) -> Path:

    portfolio = build_portfolio_summary(
        summaries,
        total_files=total_files,
        failed_forms=failed_forms,
    )

    report = render_portfolio_markdown(
        portfolio
    )

    output_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    output_path = (
        output_dir
        / "F2A_PORTFOLIO_SUMMARY.md"
    )

    output_path.write_text(
        report,
        encoding="utf-8",
    )

    return output_path